### ISSUE TITLE
AttributeError: Can't get attribute 'DataEdgeAttr' on <module 'torch_geometric.data.data' from torch_geometric/data/data.py

### ISSUE THREAD

**Issue by Infinempty** [KiddoZhu/NBFNet-PyG#13]
Traceback (most recent call last):
  File "script/run.py", line 198, in <module>
    dataset = util.build_dataset(cfg)
  File "/data/suyongye/NBFNet-PyG-master/nbfnet/util.py", line 156, in build_dataset
    dataset = WordNet18RR(**cfg.dataset)
  File "/data/suyongye/envs/myenv/lib/python3.8/site-packages/torch_geometric/datasets/word_net.py", line 134, in __init__
    self.data, self.slices = torch.load(self.processed_paths[0])
  File "/data/suyongye/envs/myenv/lib/python3.8/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/data/suyongye/envs/myenv/lib/python3.8/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'DataEdgeAttr' on <module 'torch_geometric.data.data' from '/data/home/envs/myenv/lib/python3.8/site-packages/torch_geometric/data/data.py'>

**Comment by Infinempty** [comment]
I install all package follow the readme.md.
This is package version listed by pip.

torch                 1.8.0+cu111
torch_geometric       2.0.0
torch-scatter         2.0.8
torch-sparse          0.6.12

**Comment by Infinempty** [comment]
remove the ~/datasets/knowledge_graphs/processed to fix it
