### ISSUE TITLE
UnicodeDecodeError: 'cp1' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

### ISSUE THREAD

**Issue by Mybigwang** [KiddoZhu/NBFNet-PyG#14]
Traceback (most recent call last):
  File "D:\github\NBFNet-PyG\script\run.py", line 216, in <module>
    train_and_validate(cfg, model, train_data, valid_data, filtered_data=filtered_data)
  File "D:\github\NBFNet-PyG\script\run.py", line 57, in train_and_validate
    pred = parallel_model(train_data, batch)
  File "D:\Anaconda3\envs\NBFNet\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda3\envs\NBFNet\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\github\NBFNet-PyG\nbfnet\models.py", line 139, in forward
    output = self.bellmanford(data, h_index[:, 0], r_index[:, 0])  # (num_nodes, batch_size, feature_dim）
  File "D:\github\NBFNet-PyG\nbfnet\models.py", line 104, in bellmanford
    hidden = layer(layer_input, query, boundary, data.edge_index, data.edge_type, size, edge_weight)
  File "D:\Anaconda3\envs\NBFNet\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda3\envs\NBFNet\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\github\NBFNet-PyG\nbfnet\layers.py", line 65, in forward
    output = self.propagate(input=input, relation=relation, boundary=boundary, edge_index=edge_index,
  File "D:\github\NBFNet-PyG\nbfnet\layers.py", line 89, in propagate
    out = self.message_and_aggregate(edge_index, **msg_aggr_kwargs)
  File "D:\github\NBFNet-PyG\nbfnet\layers.py", line 157, in message_and_aggregate
    from .rspmm import generalized_rspmm
  File "D:\github\NBFNet-PyG\nbfnet\rspmm\__init__.py", line 1, in <module>
    from .rspmm import generalized_rspmm
  File "D:\github\NBFNet-PyG\nbfnet\rspmm\rspmm.py", line 204, in <module>
    rspmm = load_extension("rspmm", [os.path.join(path, "rspmm.cpp"), os.path.join(path, "rspmm.cu")])
  File "D:\github\NBFNet-PyG\nbfnet\rspmm\rspmm.py", line 199, in load_extension
    return cpp_extension.load(name, sources, extra_cflags, extra_cuda_cflags, **kwargs)
  File "D:\Anaconda3\envs\NBFNet\lib\site-packages\torch\utils\cpp_extension.py", line 1314, in load
    return _jit_compile(
  File "D:\Anaconda3\envs\NBFNet\lib\site-packages\torch\utils\cpp_extension.py", line 1721, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\Anaconda3\envs\NBFNet\lib\site-packages\torch\utils\cpp_extension.py", line 1833, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\Anaconda3\envs\NBFNet\lib\site-packages\torch\utils\cpp_extension.py", line 2119, in _run_ninja_build
    message += f": {error.output.decode(*SUBPROCESS_DECODE_ARGS)}"  # type: ignore[union-attr]
  File "D:\Anaconda3\envs\NBFNet\lib\encodings\oem.py", line 15, in decode
    return oem_decode(input, errors, True)
UnicodeDecodeError: 'cp1' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

**Comment by Mybigwang** [comment]
im not sure if someone has met the problem, the problem always emerged when i try to do some encode or decode operations. if there are some extensions has some problem?

**Comment by Mybigwang** [comment]
please help
