### ISSUE TITLE
ImportError: No module named 'rspmm'

### ISSUE THREAD

**Issue by moguizhizi** [KiddoZhu/NBFNet-PyG#5]
```
Traceback (most recent call last):
  File "script/run.py", line 216, in <module>
    train_and_validate(cfg, model, train_data, valid_data, filtered_data=filtered_data)
  File "script/run.py", line 57, in train_and_validate
    pred = parallel_model(train_data, batch)
  File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sk/project/NBFNet-PyG/nbfnet/models.py", line 139, in forward
    output = self.bellmanford(data, h_index[:, 0], r_index[:, 0])  # (num_nodes, batch_size, feature_dim）
  File "/home/sk/project/NBFNet-PyG/nbfnet/models.py", line 104, in bellmanford
    hidden = layer(layer_input, query, boundary, data.edge_index, data.edge_type, size, edge_weight)
  File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sk/project/NBFNet-PyG/nbfnet/layers.py", line 66, in forward
    edge_type=edge_type, size=size, edge_weight=edge_weight)
  File "/home/sk/project/NBFNet-PyG/nbfnet/layers.py", line 89, in propagate
    out = self.message_and_aggregate(edge_index, **msg_aggr_kwargs)
  File "/home/sk/project/NBFNet-PyG/nbfnet/layers.py", line 157, in message_and_aggregate
    from nbfnet.rspmm import generalized_rspmm
  File "/home/sk/project/NBFNet-PyG/nbfnet/rspmm/__init__.py", line 1, in <module>
    from .rspmm import generalized_rspmm
  File "/home/sk/project/NBFNet-PyG/nbfnet/rspmm/rspmm.py", line 205, in <module>
    rspmm = load_extension("rspmm", [os.path.join(path, "rspmm.cpp"), os.path.join(path, "rspmm.cu")])
  File "/home/sk/project/NBFNet-PyG/nbfnet/rspmm/rspmm.py", line 199, in load_extension
    return cpp_extension.load(name, sources, extra_cflags, extra_cuda_cflags, **kwargs)
  File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1317, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1699, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'rspmm'
```

Why？Can you tell me？

**Comment by KiddoZhu** [comment]
rspmm is automatically compiled on-the-fly. This might result from a compilation failure in ninja. Could you try to delete the compilation cache with `rf -rm $TORCH_EXTENSIONS_DIR`?

**Comment by GCTTTTTT** [comment]
> ```
> Traceback (most recent call last):
>   File "script/run.py", line 216, in <module>
>     train_and_validate(cfg, model, train_data, valid_data, filtered_data=filtered_data)
>   File "script/run.py", line 57, in train_and_validate
>     pred = parallel_model(train_data, batch)
>   File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/sk/project/NBFNet-PyG/nbfnet/models.py", line 139, in forward
>     output = self.bellmanford(data, h_index[:, 0], r_index[:, 0])  # (num_nodes, batch_size, feature_dim）
>   File "/home/sk/project/NBFNet-PyG/nbfnet/models.py", line 104, in bellmanford
>     hidden = layer(layer_input, query, boundary, data.edge_index, data.edge_type, size, edge_weight)
>   File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/sk/project/NBFNet-PyG/nbfnet/layers.py", line 66, in forward
>     edge_type=edge_type, size=size, edge_weight=edge_weight)
>   File "/home/sk/project/NBFNet-PyG/nbfnet/layers.py", line 89, in propagate
>     out = self.message_and_aggregate(edge_index, **msg_aggr_kwargs)
>   File "/home/sk/project/NBFNet-PyG/nbfnet/layers.py", line 157, in message_and_aggregate
>     from nbfnet.rspmm import generalized_rspmm
>   File "/home/sk/project/NBFNet-PyG/nbfnet/rspmm/__init__.py", line 1, in <module>
>     from .rspmm import generalized_rspmm
>   File "/home/sk/project/NBFNet-PyG/nbfnet/rspmm/rspmm.py", line 205, in <module>
>     rspmm = load_extension("rspmm", [os.path.join(path, "rspmm.cpp"), os.path.join(path, "rspmm.cu")])
>   File "/home/sk/project/NBFNet-PyG/nbfnet/rspmm/rspmm.py", line 199, in load_extension
>     return cpp_extension.load(name, sources, extra_cflags, extra_cuda_cflags, **kwargs)
>   File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1091, in load
>     keep_intermediates=keep_intermediates)
>   File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1317, in _jit_compile
>     return _import_module_from_library(name, build_directory, is_python_module)
>   File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1699, in _import_module_from_library
>     file, path, description = imp.find_module(module_name, [path])
>   File "/root/anaconda3/envs/NBF_PYG_ENV/lib/python3.7/imp.py", line 296, in find_module
>     raise ImportError(_ERR_MSG.format(name), name=name)
> ImportError: No module named 'rspmm'
> ```
> 
> Why？Can you tell me？

the same, have you solved it?
